name: GetBack
version: '${project.version}'
main: get_back_plugin.get_back.Get_back
api-version: 1.19
authors: [ RaveHunter05 ]
description: Plugin to get back after death
commands:
  back:
    description: Get back to the last instance you were
  death:
    description: Get back to the last point where you died